#!/bin/bash

APPDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/
TMPDIR=${APPDIR}tmp/
XAMPPDIR=/opt/lampp/
XCPDIR=~/.local/share/applications/ #Xampp Control Panel = XCP (Directory that holds xampp-control-panel.desktop)
HTDOCSDIR=${XAMPPDIR}htdocs/

XAMPP_LATEST="7.0.6"
XAMPP_VERSION=$XAMPP_LATEST

OSBIT=""
CHOSENINST=""
TMPINSTFILE=""

function add_run_xampp_on_startup() {
    sudo sed -i -e '$i/opt/lampp/lampp start\n' /etc/rc.local
}

function add_to_path() {
    #add symlink to bin
    sudo ln -sf ${XAMPPDIR}lampp /bin/
    #all these lines bellow work. I just think its simplier this way
    #echo "Adding xampp directory to path"   
    #echo 'export PATH="/opt/lampp:$PATH"' >> ~/.bashrc
    #sudo sh -c "sed -i 's/^PATH=\"/PATH=\"\/opt\/lampp:/g' /etc/environment"
    echo "Done"
}

function add_xcp() {
    if [ -f "${XAMPPDIR}manager-linux-x64.run" ]; then
        cp -f ${APPDIR}xampp-control-panel/xampp-control-panel-x64.desktop $XCPDIR
    elif [ -f "${XAMPPDIR}manager-linux.run" ]; then
        cp -f ${APPDIR}xampp-control-panel/xampp-control-panel.desktop $XCPDIR
    fi
}

function remove_xpc() {
    sudo rm -f ${XCPDIR}xampp-control-panel*
}

function get_osbit() {
    if [ $(getconf LONG_BIT) == "64" ]; then
        echo "64"
    else
        echo "32"
    fi
}

function get_installer_url() {
    local prefix=""
    if [ $OSBIT == "64" ]; then
        prefix="-x64"
    fi
    echo "https://www.apachefriends.org/xampp-files/${XAMPP_VERSION}/xampp-linux${prefix}-${XAMPP_VERSION}-0-installer.run"
}

function execute_install() {
    sudo chmod 774 $TMPINSTFILE
    clear
    echo "Installing XAMPP ${XAMPP_VERSION} - ${OSBIT}bit"
    echo "Waiting for response"
    sudo $TMPINSTFILE --mode text
}

function get_installed_xampp_version() {
    if [ -f "${XAMPPDIR}lib/VERSION" ]; then
        echo $(cat ${XAMPPDIR}lib/VERSION)
    else 
        echo ""
    fi
}
function remove_from_path() {
    if [ -f "/bin/lampp" ]; then
        sudo rm -f /bin/lampp
    fi
}
function remove_run_xampp_on_startup() {
    sudo sed -i -e '/^\/opt\/lampp\/lampp start/d' /etc/rc.local
}

function set_xampp_security() {
    clear
    echo "Adding security"
    sudo ${XAMPPDIR}xampp security
}

function download_xampp() {
    sudo wget -nc $CHOSENINST -O $TMPINSTFILE
}

function xampp_exists() {
    if [ -f "${XAMPPDIR}xampp" ] &&  [ -f "${XAMPPDIR}lib/VERSION" ] && [ -f "${XAMPPDIR}uninstall" ]; then
        echo "true"
    else 
        echo "false"
    fi
}

# INST64_MD5SUM="90b7ead5b2725a41851eeb87866256d3"
# INST32_MD5SUM="0ce7501acf0033e071c1e0e159aa5bc4"
# function xampp_md5sum() {
#     if [ -f "$TMPINSTFILE" ]; then
#         TMP_MD5SUM=$(md5sum $TMPINSTFILE | awk '{print $1}')
#         if [ "$OSBIT" == "64" ] && [ "$TMP_MD5SUM" == "$INST64_MD5SUM" ]; then
#             echo "true"
#         elif [ "$OSBIT" == "32" ] && [ "$TMP_MD5SUM" == "$INST32_MD5SUM" ]; then
#             echo "true"
#         else
#             echo "false"
#         fi
#     else
#         echo "false"
#     fi
# }

function restart_xampp() {
    echo "Restarting xampp server"
    sudo ${XAMPPDIR}xampp restart
}

function stop_xampp() {
    echo "Stopping xampp server"
    sudo ${XAMPPDIR}lampp stop
}

function install_xampp() {
    if [ $(xampp_exists) == "true" ]; then
        echo "XAMPP $(get_installed_xampp_version) already exists on your computer!"
        help
        exit
    fi
    download_xampp
    execute_install
    if [ $(xampp_exists) != "true" ]; then
        echo -e "If you see this message then xampp was not installed as it should be."
        echo "Possible reasons:"
        echo "1.) Installer file is corrupted did not finish downloading"
        echo "2.) Chosen installation version does not exist"
        echo "3.) Other"
        echo "Try to install xampp again!"
        rm -f ${TMPINSTFILE}
        return 0
    fi
    sudo chown $(whoami) -R ${HTDOCSDIR}
    add_to_path
    restart_xampp
    set_xampp_security
    add_run_xampp_on_startup
    add_xcp
    # sudo chown $(whoami) -R ${HTDOCSDIR}
    # sudo chmod 750 -R ${XAMPPDIR}
    # sudo chmod 755 -R ${HTDOCSDIR}
}

function uninstall_xampp() {
    if [ $(xampp_exists) != "true" ]; then
        echo "Xampp does not exist!"
        return 0
    fi

    clear
    echo "Removing xampp installation"
    stop_xampp
    sudo chmod 774 ${XAMPPDIR}uninstall*
    sudo ${XAMPPDIR}uninstall --mode text
    remove_from_path
    remove_run_xampp_on_startup
    remove_xpc
    #method below works
    #sudo sed -i.bak '/export PATH="\/opt\/lampp:$PATH/d' .bashrc
    echo "Done uninstaling xampp!"
}

function help() {
    echo "Usage: xamppfresh <action>"
    echo "install        Installs xampp on your computer"
    echo "uninstall      Uninstall xampp completely from your computer. *"
    echo "*  Be sure to backup your files and databases, before you execute action!!!"
}

#end of definitions 



OSBIT=$(get_osbit)
if [ $# == 2 ] && [ $1 == "install" ]; then 
    XAMPP_VERSION=$2
fi
TMPINSTFILE=${TMPDIR}installer-${OSBIT}-${XAMPP_VERSION}.run
CHOSENINST=$(get_installer_url)

if [ $# -ge 1 ]; then
    if [ $1 == "install" ]; then
        install_xampp
    elif [ $1 == "uninstall" ]; then
        uninstall_xampp
    fi
else
    help
fi